### ISSUE TITLE
Recommended card is JC 2.1.1 and applet installation fails

### ISSUE THREAD

**Issue by jacobsevart** [martinpaljak/GlobalPlatformPro#29]
I purchased a couple of SmartCafe Expert 3.2 cards per the Wiki's recommendation, but this model uses JavaCard 2.2.1. Consequently, I was not able to install any applets on them. All the ones I tried - MuscleApplet, IsoApplet, and ykneo-openpgp - failed with an error similar to this one. (Unlocking was successful, though.)

```
➜  GlobalPlatformPro git:(master) ✗ gp -install AppletPlayground/MuscleApplet.cap -default
Applet loading failed. Are you sure the CAP file (JC version, packages) is compatible with your card?
pro.javacard.gp.GPException: LOAD failed SW: 6A80
	at pro.javacard.gp.GlobalPlatform.check(GlobalPlatform.java:1092)
	at pro.javacard.gp.GlobalPlatform.loadCapFile(GlobalPlatform.java:728)
	at pro.javacard.gp.GlobalPlatform.loadCapFile(GlobalPlatform.java:686)
	at pro.javacard.gp.GPTool.main(GPTool.java:471)
➜  GlobalPlatformPro git:(master) ✗
```

I assume this error is referring to the fact that the card is JC 2.2.1. Is it possible to compile any OpenSC-compatible applet for 2.2.1? If not, I would recommend removing any 2.2.1 cards/purchase links from the hardware recommendations.

**Comment by martinpaljak** [comment]
From *global platform* perspective, the card is "OK". Make sure you compile your applet against 2.2.1 (no ExtendedAPDU for example), for example with ant-javacard: https://github.com/martinpaljak/ant-javacard#syntax

Of course, I would like to suggest the latest and greatest cards, but it all depends on the target application and requirements. I'm sure any specific applet can give suggestions (read: should clearly document) on what is the recommended card and what are the minimal requirements for the app/card combo.

I'll make it so that the requirements to carefully consider your cards would be more visible in the readme.

**Comment by martinpaljak** [comment]
To quote the ["JavaCard Buyer's Guide"](https://github.com/martinpaljak/GlobalPlatformPro/tree/master/docs/JavaCardBuyersGuide):

> What to ask / look out for
> JavaCard version: 2.2.2, with 3.0.1 and 3.0.4 becoming popular. Bigger is better but for actual rollout check the necessary features, algorithms and maybe try to aim for 2.2.2-compatible code.

Also, from GlobalPlatformPro perspective, the JavaCard version and features does not matter. I updated the TestedCards page to note that the list is incomplete and in no particular order (in real life I've not found a JavaCard that does NOT work with GPPro, except some Chinese ones that require slight patching (present in trunk)).

Luckily the SCE 3.2 cards are still useful for simple apps and pretty cheap compared to some newer JC3 cards that can go for 3 times the price for a single card :)
