### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by 0xbaadf00d** [martinpaljak/GlobalPlatformPro#69]
Hello,

When do you plan to release the next version of GP ?

Commits since the last release: https://github.com/martinpaljak/GlobalPlatformPro/compare/v0.3.9...master

Sincerly.

**Comment by martinpaljak** [comment]
Yes, a release is overdue.
Some meaningful things related to security domains need to be smoothened before a next meaningful release, but a point release can be made "just because". What exactly is the problem point with current version?

A next major release is expected with a web-frontend for card management via [web-eid.js](https://github.com/web-eid/web-eid.js#pcsc-operations) but that is probably happening in a month or so.

**Comment by 0xbaadf00d** [comment]
Ok. 

I have another question, can I use gp.jar as a simple lib to give ability to my client application to install CAP file on a JavaCard ? 

By instance, for a simple wallet applet, my custom application will read the card balance, uninstall application, install new CAP file and restore card balance.

**Comment by dancvrcek** [comment]
Quite keen to hear an update here with respect to web-eid.js :) We use it this way for our RESTful server built on top of gppro (the project is to create "cloud smart cards") but we had to mod the main() into a class method.

**Comment by martinpaljak** [comment]
@0xbaadf00d yes you can, unfortunately the API must be investigated by looking at GPTool.jar, mostly, the docs are not that great and the [API](http://martinpaljak.github.io/GlobalPlatformPro/) is not fixed in stone (not updated that often)

@dancvrcek web-eid is the opposite of "cloud smart cards", it is about exposing client side cards and readers to websites, in a controlled and meaningful way.

**Comment by martinpaljak** [comment]
A huge rewrite of the internals is coming in a few days. It also changes quite a bit (but IMHO makes it more logical) the command line interface, key handling and supplementary security domain handling.

**Comment by martinpaljak** [comment]
https://github.com/martinpaljak/GlobalPlatformPro/releases/tag/v0.3.10rc3

This is far from complete (a pre-release), but feedback is most welcome. The final release will have 0.4 as a version.
